### ISSUE TITLE
Issue migrating to 12.0.0

### ISSUE THREAD

**Issue by bruhalm** [keycloak/keycloak-community#204]
I am getting the following issue migrating from 11.0.3 to 12.0.0

17:01:51,321 FATAL [org.keycloak.services] (ServerService Thread Pool -- 72) Error during startup: org.keycloak.models.ModelDuplicateException: javax.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session : [org.keycloak.models.jpa.entities.RequiredActionProviderEntity#aa130700-94e5-47ab-bf53-38c584908b83]
	at org.keycloak.keycloak-model-jpa@12.0.0//org.keycloak.connections.jpa.PersistenceExceptionConverter.convert(PersistenceExceptionConverter.java:59)
	at org.keycloak.keycloak-model-jpa@12.0.0//org.keycloak.connections.jpa.PersistenceExceptionConverter.invoke(PersistenceExceptionConverter.java:51)
	at javax.persistence.api@2.2.3//com.sun.proxy.$Proxy90.persist(Unknown Source)
	at org.keycloak.keycloak-model-jpa@12.0.0//org.keycloak.models.jpa.RealmAdapter.addRequiredActionProvider(RealmAdapter.java:1826)
	at org.keycloak.keycloak-model-infinispan@12.0.0//org.keycloak.models.cache.infinispan.RealmAdapter.addRequiredActionProvider(RealmAdapter.java:1359)
	at org.keycloak.keycloak-server-spi-private@12.0.0//org.keycloak.migration.migrators.MigrateTo12_0_0.lambda$migrate$4(MigrateTo12_0_0.java:52)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.keycloak.keycloak-server-spi-private@12.0.0//org.keycloak.migration.migrators.MigrateTo12_0_0.migrate(MigrateTo12_0_0.java:52)
	at org.keycloak.keycloak-server-spi-private@12.0.0//org.keycloak.migration.MigrationModelManager.migrate(MigrationModelManager.java:111)
	at org.keycloak.keycloak-services@12.0.0//org.keycloak.services.resources.KeycloakApplication.migrateModel(KeycloakApplication.java:234)
	at org.keycloak.keycloak-services@12.0.0//org.keycloak.services.resources.KeycloakApplication.migrateAndBootstrap(KeycloakApplication.java:175)
	at org.keycloak.keycloak-services@12.0.0//org.keycloak.services.resources.KeycloakApplication$1.run(KeycloakApplication.java:138)
	at org.keycloak.keycloak-server-spi-private@12.0.0//org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:228)
	at org.keycloak.keycloak-services@12.0.0//org.keycloak.services.resources.KeycloakApplication.startup(KeycloakApplication.java:129)
	at org.keycloak.keycloak-wildfly-extensions@12.0.0//org.keycloak.provider.wildfly.WildflyPlatform.onStartup(WildflyPlatform.java:29)
	at org.keycloak.keycloak-services@12.0.0//org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:115)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:152)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2815)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:371)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.startInternal(ResteasyDeployment.java:283)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:93)

looks like this might be an attempt to fix it 

https://github.com/keycloak/keycloak/pull/7685

**Comment by hmlnarik** [comment]
Thank you for the report. To keep single source of the issue, closing this issue. Please refer to https://issues.redhat.com/browse/KEYCLOAK-16648 instead.
