### ISSUE TITLE
Wrong logout uri in org.keycloak.adapters.ServerRequest.invokeLogout

### ISSUE THREAD

**Issue by marcuskmw** [keycloak/keycloak-community#221]
**Background**
* Use image quay.io/keycloak/keycloak:12.0.2
* Deploy in k8s cluster
* User access keycloak at frontend url (i.e. http://frontend.keycloak.url/auth/)
* Spring boot application access backend url keycloak at (i.e. http://backend.keycloak.service/auth/)
* Spring boot application can't access the frontend url of the keycloak
* Spring boot use Keycloak adapter Version 12.0.2 

**Settings**
* Create a realm `xxx` with Frontend URL=http://frontend.keycloak.url/auth/
* In spring boot application.yaml, keycloak.auth-server-url set to http://backend.keycloak.service/auth/ 

**Expected result**
When spring boot calling request.logout(), it should trigger keycloak adapter to post a logout call via backend url

**Found error**
ServiceRequest.invokeLogout call http://frontend.keycloak.url/auth/realms/xxx/protocol/openid-connect/logout
and got the following error
```
[ERROR][nio-8080-exec-1 (1)][pters.RefreshableKeycloakSecurityContext:86  ] failed to invoke remote logout
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:?]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242) ~[?:?]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403) ~[?:?]
	at java.net.Socket.connect(Socket.java:609) ~[?:?]
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:605) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:440) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[httpclient-4.5.13.jar:4.5.13]
	at org.keycloak.adapters.ServerRequest.invokeLogout(ServerRequest.java:82) ~[keycloak-adapter-core-12.0.2.jar:12.0.2]
	at org.keycloak.adapters.RefreshableKeycloakSecurityContext.logout(RefreshableKeycloakSecurityContext.java:84) [keycloak-adapter-core-12.0.2.jar:12.0.2]
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.logoutInternal(AbstractKeycloakAuthenticatorValve.java:82) [spring-boot-container-bundle-12.0.2.jar:12.0.2]
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.logout(KeycloakAuthenticatorValve.java:91) [spring-boot-container-bundle-12.0.2.jar:12.0.2]
	at org.apache.catalina.connector.Request.logout(Request.java:2787) [tomcat-embed-core-9.0.41.jar:9.0.41]
	at org.apache.catalina.connector.RequestFacade.logout(RequestFacade.java:1092) [tomcat-embed-core-9.0.41.jar:9.0.41]
...
```

**Comment by marcuskmw** [comment]
same case as https://issues.redhat.com/browse/KEYCLOAK-16372
