### ISSUE TITLE
Keycloak cannot verify user information with a valid token

### ISSUE THREAD

**Issue by toannh0104** [keycloak/keycloak-community#224]
Env: 
- Binary keycloak-12.0.0.zip
- Java 11
- Documentation: https://github.com/keycloak/keycloak-documentation/blob/master/securing_apps/topics/oidc/oidc-generic.adoc

POST http://127.0.0.1:8080/auth/realms/test/protocol/openid-connect/token
 {
     client_secret: ...,
     grant_type: ...,
     client_id: ...,
 }
response
{
    "access_token": "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIxOE..."
    "expires_in": 3600,
    ....
}

GET http://127.0.0.1:8080/auth/realms/test/protocol/openid-connect/userinfo Header: Bearer ${access_token}

exception in the server's console 

![image](https://user-images.githubusercontent.com/17583795/106161615-ce204f00-61b9-11eb-8d7a-f61c45ec141f.png)

The issue happened on Keycloak 12.0.0 but **11.0.3 work fine**

Discussion thread https://stackoverflow.com/questions/65936384/keycloak-cannot-verify-user-information-with-a-valid-token

**Comment by shivan** [comment]
fyi: seems to be also present in 12.0.2:

```
14:25:22,602 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-1) Uncaught server error: java.lang.NullPointerException: Null keys are not supported!
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.CacheImpl.assertKeyNotNull(CacheImpl.java:199)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:538)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.CacheImpl.get(CacheImpl.java:534)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.AbstractDelegatingCache.get(AbstractDelegatingCache.java:439)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.EncoderCache.get(EncoderCache.java:696)
        at org.infinispan@11.0.4.Final//org.infinispan.cache.impl.AbstractDelegatingCache.get(AbstractDelegatingCache.java:439)
        at org.keycloak.keycloak-model-infinispan@12.0.2//org.keycloak.models.sessions.infinispan.changes.InfinispanChangelogBasedTransaction.get(InfinispanChangelogBasedTransaction.java:121)
        at org.keycloak.keycloak-model-infinispan@12.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionEntity(InfinispanUserSessionProvider.java:264)
        at org.keycloak.keycloak-model-infinispan@12.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSession(InfinispanUserSessionProvider.java:258)
        at org.keycloak.keycloak-model-infinispan@12.0.2//org.keycloak.models.sessions.infinispan.InfinispanUserSessionProvider.getUserSessionWithPredicate(InfinispanUserSessionProvider.java:354)
        at org.keycloak.keycloak-services@12.0.2//org.keycloak.services.managers.UserSessionCrossDCManager.getUserSessionWithClient(UserSessionCrossDCManager.java:46)
        at org.keycloak.keycloak-services@12.0.2//org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.findValidSession(UserInfoEndpoint.java:275)
        at org.keycloak.keycloak-services@12.0.2//org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfo(UserInfoEndpoint.java:190)
        at org.keycloak.keycloak-services@12.0.2//org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfoPost(UserInfoEndpoint.java:125)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by brunomedeirosdedalus** [comment]
It is also in 12.0.2

**Comment by dreamcrash** [comment]
It seems to working with keycloak (12.0.2) deployed on docker

**Comment by stianst** [comment]
Hi, thanks for reporting, but this is not the correct replace to report issues for Keycloak. See https://www.keycloak.org/community for more information.
