### ISSUE TITLE
ConcurrentModificationException in script cache of JSPolicyProviderFactory

### ISSUE THREAD

**Issue by segersb** [keycloak/keycloak-community#261]
When starting Keycloak, we often get a ConcurrentModificationException.
The cause is located in the ScriptCache class of the JavaScript authorization policy provider.
https://github.com/keycloak/keycloak/blob/master/authz/policy/common/src/main/java/org/keycloak/authorization/policy/provider/js/ScriptCache.java

This class uses a unsynchronized list as cache
```
        cache = new LinkedHashMap<String, CacheEntry>(16, DEFAULT_LOAD_FACTOR, true) {
            @Override
            protected boolean removeEldestEntry(Map.Entry eldest) {
                return cache.size()  > maxEntries;
            }
        };

```
Maybe wrap this with Collections.synchronizedMap ?

Note the exception is also in 12.0.4.

Caused by: java.util.ConcurrentModificationException
     at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.js.ScriptCache.computeIfAbsent(ScriptCache.java:80)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.js.JSPolicyProviderFactory.getEvaluatableScript(JSPolicyProviderFactory.java:106)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.js.JSPolicyProvider.evaluate(JSPolicyProvider.java:46)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.aggregated.AggregatePolicyProvider.evaluate(AggregatePolicyProvider.java:66)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.permission.AbstractPermissionProvider.evaluate(AbstractPermissionProvider.java:56)
     at org.keycloak.keycloak-authz-policy-common@11.0.3//org.keycloak.authorization.policy.provider.permission.ScopePolicyProvider.evaluate(ScopePolicyProvider.java:52)

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
