### ISSUE TITLE
KeycloakSession.getContext().getUri() throws NullPointerException

### ISSUE THREAD

**Issue by Kayes-Islam** [keycloak/keycloak-community#285]
I am trying to generate a JWT access token from within User Storage SPI so that I can use this toke to call API to store user data.
I have access to the KeycloakSession object as passed in by to my UserStorageProviderFactory.create().

When I call `session.getContext().getUri()` throws NullPointerException:
```
keycloak-local  | Caused by: java.lang.NullPointerException
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.url.DefaultHostnameProvider.resolveUri(DefaultHostnameProvider.java:83)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.url.DefaultHostnameProvider.getScheme(DefaultHostnameProvider.java:38)
keycloak-local  |       at org.keycloak.keycloak-server-spi@13.0.1//org.keycloak.models.KeycloakUriInfo.<init>(KeycloakUriInfo.java:46)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:78)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.services.DefaultKeycloakContext.getContextPath(DefaultKeycloakContext.java:67)
```
Similar error occurs when calling session.getContext().getUri(UrlType.BACKEND). Is there anyway I can get the URL of the realm from within the Storage SPI?

**Comment by Kayes-Islam** [comment]
Here's bit more of the stack trace:
```
keycloak-local  | 02:15:12,419 INFO  [org.my-organisation.keycoak.storage_spi.ExternalUserStorageProvider] (default task-1) ExternalUserStorageProvider.Constructor()
keycloak-local  | 02:15:12,419 INFO  [org.my-organisation.keycoak.storage_spi.services.ExternalUserService] (default task-1) ExternalUserProviderService.buildClient()
keycloak-local  | 02:15:12,433 INFO  [org.my-organisation.keycoak.storage_spi.services.ExternalUserService] (default task-1) Realm name: master@bf8d2a62
keycloak-local  | 02:15:12,433 ERROR [org.my-organisation.keycoak.storage_spi.services.ExternalUserService] (default task-1) null
keycloak-local  | 02:15:12,433 ERROR [org.my-organisation.keycoak.storage_spi.services.ExternalUserService] (default task-1) Exception while calling REST-Service getUsers: javax.ws.rs.ProcessingException: java.lang.NullPointerException
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:673)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:461)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:152)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
keycloak-local  |       at deployment.my-organisation-keycloak-custom-spi.jar//com.sun.proxy.$Proxy129.getUsers(Unknown Source)
keycloak-local  |       at deployment.my-organisation-keycloak-custom-spi.jar//org.my-organisation.keycoak.storage_spi.services.ExternalUserService.getUsers(ExternalUserService.java:124)
keycloak-local  |       at deployment.my-organisation-keycloak-custom-spi.jar//org.my-organisation.keycoak.storage_spi.ExternalUserStorageProvider.searchForUser(ExternalUserStorageProvider.java:138)
keycloak-local  |       at org.keycloak.keycloak-server-spi@13.0.1//org.keycloak.storage.user.UserQueryProvider.searchForUserStream(UserQueryProvider.java:242)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.storage.UserStorageManager.lambda$searchForUserStream$13(UserStorageManager.java:369)
keycloak-local  |       at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
keycloak-local  |       at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:302)
keycloak-local  |       at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:723)
keycloak-local  |       at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720)
keycloak-local  |       at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
keycloak-local  |       at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
keycloak-local  |       at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
keycloak-local  |       at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
keycloak-local  |       at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
keycloak-local  |       at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
keycloak-local  |       at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
keycloak-local  |       at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:502)
keycloak-local  |       at com.fasterxml.jackson.datatype.jackson-datatype-jdk8@2.12.1//com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:71)
keycloak-local  |       at com.fasterxml.jackson.datatype.jackson-datatype-jdk8@2.12.1//com.fasterxml.jackson.datatype.jdk8.StreamSerializer.serialize(StreamSerializer.java:15)
keycloak-local  |       at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
keycloak-local  |       at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:400)
keycloak-local  |       at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1510)
keycloak-local  |       at com.fasterxml.jackson.core.jackson-databind@2.12.1//com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1006)
keycloak-local  |       at org.jboss.resteasy.resteasy-jackson2-provider@3.15.1.Final//org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:328)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.writeTo(AbstractWriterInterceptorContext.java:137)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:61)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:124)
keycloak-local  |       at org.jboss.resteasy.resteasy-crypto@3.15.1.Final//org.jboss.resteasy.security.doseta.DigitalSigningInterceptor.aroundWriteTo(DigitalSigningInterceptor.java:147)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:129)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$2(ServerResponseWriter.java:151)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:399)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:219)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:95)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:69)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:530)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:461)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
keycloak-local  |       at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
keycloak-local  |       at org.keycloak.keycloak-wildfly-extensions@13.0.1//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
keycloak-local  |       at org.keycloak.keycloak-wildfly-extensions@13.0.1//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)       
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)      
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
keycloak-local  |       at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
keycloak-local  |       at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
keycloak-local  |       at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
keycloak-local  |       at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
keycloak-local  |       at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
keycloak-local  |       at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
keycloak-local  |       at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
keycloak-local  |       at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
keycloak-local  |       at java.base/java.lang.Thread.run(Thread.java:829)
keycloak-local  | Caused by: java.lang.NullPointerException
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.url.DefaultHostnameProvider.resolveUri(DefaultHostnameProvider.java:83)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.url.DefaultHostnameProvider.getScheme(DefaultHostnameProvider.java:38)
keycloak-local  |       at org.keycloak.keycloak-server-spi@13.0.1//org.keycloak.models.KeycloakUriInfo.<init>(KeycloakUriInfo.java:46)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.services.DefaultKeycloakContext.getUri(DefaultKeycloakContext.java:78)
keycloak-local  |       at org.keycloak.keycloak-services@13.0.1//org.keycloak.services.DefaultKeycloakContext.getContextPath(DefaultKeycloakContext.java:67)
keycloak-local  |       at deployment.my-organisation-keycloak-custom-spi.jar//org.my-organisation.keycoak.storage_spi.services.AuthFilter.generateJwtToken(AuthFilter.java:86)
keycloak-local  |       at deployment.my-organisation-keycloak-custom-spi.jar//org.my-organisation.keycoak.storage_spi.services.AuthFilter.filter(AuthFilter.java:58)
keycloak-local  |       at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:660)
keycloak-local  |       ... 100 more
keycloak-local  |
keycloak-local  | 02:15:12,436 INFO  [org.my-organisation.keycoak.storage_spi.ExternalUserStorageProvider] (default task-1) ExternalUserStorageProvider.Close().
```

**Comment by stianst** [comment]
This is not the correct place to report bugs or ask for help. Please see https://www.keycloak.org/community for more information.
