### ISSUE TITLE
Bypass Failing certificate chain validation for Keycloak 13.0+ for In-House Certificates that we cannot change.

### ISSUE THREAD

**Issue by SomeDeveloper13** [keycloak/keycloak-community#296]
We're unable to upgrade to Keycloak 13.0.
The certificate validation is rejecting our certificate chain with the following error.

Is there a way to use the old validation, or overwrite the validation with our own if Keycloak can't handle custom certificates.

Error:
```
Exception in thread "main" java.lang.RuntimeException: Invalid certificate chain. Check the order of certificates.
    at JavaKeystoreKeyProviderTest.loadKey(JavaKeystoreKeyProviderTest.java:61)
    at JavaKeystoreKeyProviderTest.main(JavaKeystoreKeyProviderTest.java:34)
Caused by: java.security.cert.CertPathValidatorException: non-null policy tree required and policy tree is null
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
    at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
    at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
    at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
    at JavaKeystoreKeyProviderTest.validateCertificateChain(JavaKeystoreKeyProviderTest.java:106)
    at JavaKeystoreKeyProviderTest.loadCertificateChain(JavaKeystoreKeyProviderTest.java:75)
    at JavaKeystoreKeyProviderTest.loadKey(JavaKeystoreKeyProviderTest.java:47)
    ... 1 more
Caused by: java.security.cert.CertPathValidatorException: non-null policy tree required and policy tree is null
    at sun.security.provider.certpath.PolicyChecker.processPolicies(PolicyChecker.java:572)
    at sun.security.provider.certpath.PolicyChecker.checkPolicy(PolicyChecker.java:225)
    at sun.security.provider.certpath.PolicyChecker.check(PolicyChecker.java:180)
    at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
    ... 8 more
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
```

**Comment by SomeDeveloper13** [comment]
Root cause:
Update to JavaKeystoreKeyProvider.java
See difference between 12.0.4 & 13.0.0
https://raw.githubusercontent.com/keycloak/keycloak/12.0.4/services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProvider.java
https://raw.githubusercontent.com/keycloak/keycloak/13.0.0/services/src/main/java/org/keycloak/keys/JavaKeystoreKeyProvider.java

**Comment by SomeDeveloper13** [comment]
Here's the chain in our keystore with certan info stripped out with placeholders:
```
Certificate[1]:
Owner: CN=Federal Common Policy CA G2, OU=FPKI, O=ZZZZZZXX, C=US
Issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=ZZZZZZXX, C=US
Serial number: 21e5b9a0cc956de278ca012ba8fdc58a98b3fbea
Valid from: Wed Oct 14 09:35:12 EDT 2020 until: Sun Oct 14 09:35:12 EDT 2040
Certificate fingerprints:
	 SHA1: 99:B4:25:1E:2E:EE:05:D8:29:2E:83:97:A9:01:65:29:3D:11:60:28
	 SHA256: 5F:9A:EC:C2:46:16:B2:19:13:72:60:0D:D8:0F:6D:D3:20:C8:CA:5A:0C:EB:7F:09:C9:85:EB:F0:69:69:34:FC
Signature algorithm name: SHA384withRSA
Subject Public Key Algorithm: 4096-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#2: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#3: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://repo.ZXXZZXE/fcpca/caCertsIssuedByfcpcag2.p7c
]
]

#4: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: F4 27 5C A9 C3 7C 47 F4   FA A6 A7 B0 59 97 AA DD  .'\...G.....Y...
0010: 35 26 17 E3                                        5&..
]
]


Certificate[2]:
Owner: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=ZZZZZZXX, C=US
Serial number: 2013db2cd30dd29d17edc48535c5e00d8916cf02
Valid from: Wed Nov 18 09:53:00 EST 2020 until: Sun Aug 14 09:53:00 EDT 2022
Certificate fingerprints:
	 SHA1: D7:D2:98:92:7D:33:9E:FA:41:4F:25:65:92:3E:28:B9:8A:CD:97:0A
	 SHA256: 20:9C:E8:4F:4B:48:11:54:2C:5C:47:54:A7:3A:9C:27:2A:E1:45:8C:04:49:3C:89:C7:4E:D6:77:3A:CA:55:3F
Signature algorithm name: SHA384withRSA
Subject Public Key Algorithm: 4096-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: caIssuers
   accessLocation: URIName: http://repo.ZXXZZXE/fcpca/caCertsIssuedTofcpcag2.p7c
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: F4 27 5C A9 C3 7C 47 F4   FA A6 A7 B0 59 97 AA DD  .'\...G.....Y...
0010: 35 26 17 E3                                        5&..
]
]

#3: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://repo.ZXXZZXE/fcpca/fcpcag2.crl]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.1]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.2]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.18]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.19]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.20]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.8]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.36]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.13]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.17]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.39]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.40]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.41]
[]  ]
]

#6: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#7: ObjectId: 2.5.29.36 Criticality=false
PolicyConstraints: [  Require: 0;	Inhibit: 0 ]

#8: ObjectId: 2.5.29.33 Criticality=false
PolicyMappings [
[CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.1]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.2]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.2]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.3]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.7]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.4]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.5]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.18]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.10]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.19]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.11]
]
, CertificatePolicyMap: [
IssuerDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.3.20]
SubjectDomain:CertificatePolicyId: [2.16.840.1.101.3.2.1.5.12]
]
]]

#9: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://pki.ZXXZZXC/root_sia.p7c
]
]

#10: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 17 4B B8 26 BA 69 7A AD   12 50 57 45 31 9E 57 BB  .K.&.iz..PWE1.W.
0010: 74 A5 DA 2F                                        t../
]
]

#11: ObjectId: 2.5.29.54 Criticality=false
Unparseable InhibitAnyPolicy extension due to
java.io.IOException: Criticality cannot be false for InhibitAnyPolicy

0000: 02 01 00                                           ...


Certificate[3]:
Owner: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Issuer: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Serial number: 570d2c00
Valid from: Sat Aug 05 10:16:30 EDT 2006 until: Wed Aug 05 10:46:30 EDT 2026
Certificate fingerprints:
	 SHA1: 30:EE:8B:72:D7:45:DA:0F:69:38:ED:13:7A:C6:04:DC:D8:A7:4A:F0
	 SHA256: B2:97:01:B9:5E:E2:50:E1:C1:3A:15:13:1C:AC:C7:C5:03:F1:F9:80:BA:10:44:F7:04:EA:DF:81:39:3F:90:A3
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: caIssuers
   accessLocation: URIName: http://pki.ZXXZZXC/cacertsissuedtotrca.p7c
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 17 4B B8 26 BA 69 7A AD   12 50 57 45 31 9E 57 BB  .K.&.iz..PWE1.W.
0010: 74 A5 DA 2F                                        t../
]
]

#3: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [CN=CRL1, OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US]
, DistributionPoint:
     [URIName: http://pki.ZXXZZXC/ZXXZZWW_Root_CA1.crl]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.8]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.13]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.17]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.36]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.39]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.40]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.41]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.2]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.3]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.4]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.7]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.10]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.11]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.12]
[]  ]
]

#6: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#7: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://pki.ZXXZZXC/root_sia.p7c
]
]

#8: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 68 84 15 48 8C 54 70 7F   2D 12 58 0E EC 1C 78 EF  h..H.Tp.-.X...x.
0010: 3C 2E 59 64                                        <.Yd
]
]


Certificate[4]:
Owner: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Issuer: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Serial number: 47e15e91
Valid from: Tue Apr 08 10:12:30 EDT 2008 until: Sat Apr 08 10:42:30 EDT 2028
Certificate fingerprints:
	 SHA1: 32:75:E9:2E:79:EF:E4:13:10:3B:CC:F5:2A:73:32:BE:45:D7:9C:29
	 SHA256: 18:AE:1F:33:90:03:47:43:0D:1B:D7:17:FE:5C:0B:35:3F:BA:F2:8B:B9:73:46:B2:3A:73:37:7D:0C:06:26:82
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.2.840.113533.7.65.0 Criticality=false
0000: 30 0E 1B 08 56 37 2E 31   3A 34 2E 30 03 02 04 90  0...V7.1:4.0....


#2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#4: ObjectId: 2.16.840.1.113730.1.1 Criticality=false
NetscapeCertType [
   SSL CA
   S/MIME CA
   Object Signing CA]

#5: ObjectId: 2.5.29.16 Criticality=false
PrivateKeyUsage: [
From: Tue Apr 08 10:12:30 EDT 2008, To: Sat Apr 08 10:42:30 EDT 2028]

#6: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://devpki.ZXXZZXY/devssproot_sia.p7c
, 
   accessMethod: caRepository
   accessLocation: URIName: ldap://devsspldap.ZXXZZXY/ou=ZZZXZZXX%20Root%20CA,ou=Certification%20Authorities,ou=ZZZXZZXY,o=CZZXZZXY,c=US?cACertificate;binary,crossCertificatePair;binary
]
]

#7: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 55 60 80 A0 12 33 CA FE   3D C2 17 9C F4 5E 42 09  U`...3..=....^B.
0010: 6C 06 42 98                                        l.B.
]
]


Certificate[5]:
Owner: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Issuer: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Serial number: 443ea73a
Valid from: Sat Aug 05 10:16:30 EDT 2006 until: Wed Aug 05 10:46:30 EDT 2026
Certificate fingerprints:
	 SHA1: 02:FF:F6:B3:FC:81:5C:57:E6:83:2D:FC:38:61:85:13:33:B0:C3:0B
	 SHA256: 5F:4F:6C:DA:1E:01:2C:E8:19:47:A5:B9:72:B7:17:8D:97:46:19:92:B0:7D:E7:E0:25:B7:DD:7A:B8:A3:A6:3B
Signature algorithm name: SHA1withRSA (weak)
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.2.840.113533.7.65.0 Criticality=false
0000: 30 0E 1B 08 56 37 2E 31   3A 34 2E 30 03 02 04 90  0...V7.1:4.0....


#2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#4: ObjectId: 2.16.840.1.113730.1.1 Criticality=false
NetscapeCertType [
   SSL CA
   S/MIME CA
   Object Signing CA]

#5: ObjectId: 2.5.29.16 Criticality=false
PrivateKeyUsage: [
From: Sat Aug 05 10:16:30 EDT 2006, To: Thu Aug 04 22:46:30 EDT 2016]

#6: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://pki.ZXXZZXY/root_sia.p7c
, 
   accessMethod: caRepository
   accessLocation: URIName: ldap://ldap.ZXXZZXY/ou=ZZZXZZXX%20Root%20CA,ou=Certification%20Authorities,ou=ZZZXZZXY,o=CZZXZZXY,c=US?cACertificate;binary,crossCertificatePair;binary
]
]

#7: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 68 84 15 48 8C 54 70 7F   2D 12 58 0E EC 1C 78 EF  h..H.Tp.-.X...x.
0010: 3C 2E 59 64                                        <.Yd
]
]


Certificate[6]:
Owner: OU=ZZZ CA4, OU=Certification Authorities, OU=ZZZZZZZZ, O=ZZZZZZXX, C=US
Issuer: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Serial number: 5ccb31ca
Valid from: Thu Jun 06 07:11:16 EDT 2019 until: Wed Jun 06 07:41:16 EDT 2029
Certificate fingerprints:
	 SHA1: 58:08:5A:64:E1:81:57:3F:4F:D9:17:C5:C0:21:EB:1C:F3:44:DD:5F
	 SHA256: 1F:87:63:21:69:31:13:EA:50:00:50:53:1A:75:57:16:F1:96:DC:05:EA:D8:49:9E:79:4D:34:1F:6C:B4:45:15
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: caIssuers
   accessLocation: URIName: http://pki.ZXXZZXC/ZXXca_aia.p7c
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 17 4B B8 26 BA 69 7A AD   12 50 57 45 31 9E 57 BB  .K.&.iz..PWE1.W.
0010: 74 A5 DA 2F                                        t../
]
]

#3: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://pki.ZXXZZXC/ZXXZZWW_Root_CA1.crl]
, DistributionPoint:
     [CN=CRL1, OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.8]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.13]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.17]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.36]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.39]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.40]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.41]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.10]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.11]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.5.12]
[]  ]
]

#6: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#7: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://pki.ZXXZZXC/ZXXca_sia.p7c
]
]

#8: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 5E 51 9D 99 EB 82 73 7F   86 10 4C 5C F8 D0 36 C6  ^Q....s...L\..6.
0010: 96 F4 2E 97                                        ....
]
]


Certificate[7]:
Owner: OU=ZZZ CA4, OU=Certification Authorities, OU=ZZZZZZZZ, O=ZZZZZZXX, C=US
Issuer: OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US
Serial number: 4e398128
Valid from: Sat Jun 13 10:35:04 EDT 2015 until: Fri Jun 13 11:05:04 EDT 2025
Certificate fingerprints:
	 SHA1: A3:1A:5D:F2:F1:C1:01:9B:9C:F5:B7:CA:4E:3B:26:65:0B:9C:A9:3F
	 SHA256: 8E:72:D7:98:24:31:C4:BD:CF:7C:2A:B2:C9:B5:B1:32:17:38:D6:58:41:B8:19:7E:AC:CE:14:2F:0A:9C:83:43
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions: 

#1: ObjectId: 1.3.6.1.5.5.7.1.1 Criticality=false
AuthorityInfoAccess [
  [
   accessMethod: caIssuers
   accessLocation: URIName: http://pki.ZXXZZXC/ZXXca_aia.p7c
]
]

#2: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 68 84 15 48 8C 54 70 7F   2D 12 58 0E EC 1C 78 EF  h..H.Tp.-.X...x.
0010: 3C 2E 59 64                                        <.Yd
]
]

#3: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#4: ObjectId: 2.5.29.31 Criticality=false
CRLDistributionPoints [
  [DistributionPoint:
     [URIName: http://pki.ZXXZZXC/ZXXZZWW_Root_CA.crl]
, DistributionPoint:
     [CN=CRL1, OU=ZZZZZZ Root CA, OU=Certification Authorities, OU=ZXXZZII, O=ZZZZZZXX, C=US]
]]

#5: ObjectId: 2.5.29.32 Criticality=false
CertificatePolicies [
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.6]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.7]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.8]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.13]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.16]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.17]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.36]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.39]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.40]
[]  ]
  [CertificatePolicyId: [2.16.840.1.101.3.2.1.3.41]
[]  ]
]

#6: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#7: ObjectId: 1.3.6.1.5.5.7.1.11 Criticality=false
SubjectInfoAccess [
  [
   accessMethod: caRepository
   accessLocation: URIName: http://pki.ZXXZZXC/ZXXca_sia.p7c
]
]

#8: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 7C C3 4A 5C BA 1F 36 AB   83 51 7D F4 E0 E5 0E 90  ..J\..6..Q......
0010: 7F 1C 13 41                                        ...A
]
]
``

**Comment by SomeDeveloper13** [comment]
This appears to be due to the CA Chain failing java policy tree validation.
I tried making an SPI to add my own custom KeyProvider, but while it says it's deployed, it doesn't show up in the dropdown.
Any Help would be greatly appreciated.

### ProviderFactory
```java
package my.spi.key;

import org.jboss.logging.Logger;
import org.keycloak.component.ComponentModel;
import org.keycloak.component.ComponentValidationException;
import org.keycloak.keys.JavaKeystoreKeyProviderFactory;
import org.keycloak.keys.KeyProvider;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.RealmModel;
import org.keycloak.provider.ConfigurationValidationHelper;

public class JavaKeystoreKeyProviderFactory_Custom extends JavaKeystoreKeyProviderFactory {
	private static final Logger logger = Logger.getLogger(JavaKeystoreKeyProviderFactory_Custom.class);

	@Override
	public KeyProvider create(KeycloakSession session, ComponentModel model) {
		return new JavaKeystoreKeyProvider_Custom(session.getContext().getRealm(), model);
	}

	@Override
	public void validateConfiguration(KeycloakSession session, RealmModel realm, ComponentModel model) throws ComponentValidationException {
//		super.validateConfiguration(session, realm, model);

		ConfigurationValidationHelper.check(model)
				.checkLong(Attributes.PRIORITY_PROPERTY, false)
				.checkBoolean(Attributes.ENABLED_PROPERTY, false)
				.checkBoolean(Attributes.ACTIVE_PROPERTY, false);

		ConfigurationValidationHelper.check(model)
				.checkSingle(KEYSTORE_PROPERTY, true)
				.checkSingle(KEYSTORE_PASSWORD_PROPERTY, true)
				.checkSingle(KEY_ALIAS_PROPERTY, true)
				.checkSingle(KEY_PASSWORD_PROPERTY, true);

		try {
			new JavaKeystoreKeyProvider_Custom(session.getContext().getRealm(), model)
					.loadKey(session.getContext().getRealm(), model);
		} catch (Throwable t) {
			logger.error("Failed to load keys.", t);
			throw new ComponentValidationException("Failed to load keys. " + t.getMessage(), t);
		}
	}

	@Override
	public String getId() {
		return "custom-java-keystore";
	}
}
```

```java
package my.spi.key;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.security.KeyPair;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;
import java.security.cert.X509Certificate;

import org.keycloak.common.util.CertificateUtils;
import org.keycloak.common.util.KeyUtils;
import org.keycloak.component.ComponentModel;
import org.keycloak.crypto.KeyWrapper;
import org.keycloak.keys.AbstractRsaKeyProvider;
import org.keycloak.models.RealmModel;

/**
 * @author <a href="mailto:sthorger@redhat.com">Stian Thorgersen</a>
 */
public class JavaKeystoreKeyProvider_Custom extends AbstractRsaKeyProvider {

	public JavaKeystoreKeyProvider_Custom(RealmModel realm, ComponentModel model) {
		super(realm, model);
	}

	@Override
	protected KeyWrapper loadKey(RealmModel realm, ComponentModel model) {
		try (FileInputStream is = new FileInputStream(model.get(JavaKeystoreKeyProviderFactory_Custom.KEYSTORE_KEY))) {
			KeyStore keyStore = KeyStore.getInstance("JKS");
			keyStore.load(is, model.get(JavaKeystoreKeyProviderFactory_Custom.KEYSTORE_PASSWORD_KEY).toCharArray());

			PrivateKey privateKey = (PrivateKey) keyStore.getKey(model.get(JavaKeystoreKeyProviderFactory_Custom.KEY_ALIAS_KEY), model.get(JavaKeystoreKeyProviderFactory_Custom.KEY_PASSWORD_KEY).toCharArray());
			PublicKey publicKey = KeyUtils.extractPublicKey(privateKey);

			KeyPair keyPair = new KeyPair(publicKey, privateKey);

			X509Certificate certificate = (X509Certificate) keyStore.getCertificate(model.get(JavaKeystoreKeyProviderFactory_Custom.KEY_ALIAS_KEY));
			if (certificate == null) {
				certificate = CertificateUtils.generateV1SelfSignedCertificate(keyPair, realm.getName());
			}

			return createKeyWrapper(keyPair, certificate);
		} catch (KeyStoreException kse) {
			throw new RuntimeException("KeyStore error on server. " + kse.getMessage(), kse);
		} catch (FileNotFoundException fnfe) {
			throw new RuntimeException("File not found on server. " + fnfe.getMessage(), fnfe);
		} catch (IOException ioe) {
			throw new RuntimeException("IO error on server. " + ioe.getMessage(), ioe);
		} catch (NoSuchAlgorithmException nsae) {
			throw new RuntimeException("Algorithm not available on server. " + nsae.getMessage(), nsae);
		} catch (CertificateException ce) {
			throw new RuntimeException("Certificate error on server. " + ce.getMessage(), ce);
		} catch (UnrecoverableKeyException uke) {
			throw new RuntimeException("Keystore on server can not be recovered. " + uke.getMessage(), uke);
		}
	}
}
```

META-INF.services/org.keycloak.keys.KeyProviderFactory
```
my.spi.key.JavaKeystoreKeyProviderFactory_Custom
```

**Comment by SomeDeveloper13** [comment]
I figured out my issues:
1) The META-INF folder was incorrect: `META-INF.services` -> `META-INF/services`
2) The classes I was extending are not accessable to the SPI code, so I had to copy the missing code down and add a few more provided jars to the pom.
    - org.jboss.logging:jboss-logging
    - org.keycloak:keycloak-server-spi
    - org.keycloak:keycloak-server-spi-private
    - org.keycloak:keycloak-common
    - org.keycloak:keycloak-core
