### ISSUE TITLE
keycloak.x start-dev fails to start

### ISSUE THREAD

**Issue by DanielJoyce** [keycloak/keycloak-community#297]
I tried running keycloak.x config and provided no values, just making sure it initialized some defaults it perhaps missed

```
❯ kc.sh start-dev
LogManager error of type WRITE_FAILURE: The delayed handler's queue was overrun and log record(s) were lost. Did you forget to configure logging?
2021-08-04 10:56:32,593 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.http.enabled] set with value [true] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,601 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.spi.theme.static-max-age] set with value [-1] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,609 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.db.username] set with value [sa] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,634 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.spi.theme.cache-templates] set with value [false] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,644 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.spi.theme.cache-themes] set with value [false] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,650 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.db.password] set with value [keycloak] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,654 WARN  [org.key.qua.KeycloakRecorder] (main) New property [kc.cluster] set with value [local] in [PropertiesConfigSource[source=keycloak.properties]]. This property is not persisted into the server image.
2021-08-04 10:56:32,654 WARN  [org.key.qua.KeycloakRecorder] (main) Please, run the 'config' command if you want to persist the new configuration into the server image:

	kc.sh config  --http-enabled=true --spi-theme-static-max-age=-1 --db-username=sa --spi-theme-cache-templates=false --spi-theme-cache-themes=false --db-password=keycloak --cluster=local

2021-08-04 10:56:33,949 WARN  [io.qua.run.con.ConfigChangeRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.package.type was 'fast-jar' at build time and is now 'mutable-jar'
2021-08-04 10:56:34,768 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Wrong user name or password [28000-197]
2021-08-04 10:56:34,772 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (main) HHH000342: Could not obtain connection to query metadata: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.validateUserAndPassword(Engine.java:341)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:165)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:189)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2021-08-04 10:56:35,339 INFO  [org.key.url.DefaultHostnameProviderFactory] (main) Frontend: <request>, Admin: <frontend>, Backend: <request>
2021-08-04 10:56:35,581 INFO  [org.key.pro.qua.QuarkusCacheManagerProvider] (main) Loading cluster configuration from /home/danieljoyce/.local/bin/keycloak.x-15.0.0/bin/../conf/cluster-local.xml
2021-08-04 10:56:35,823 WARN  [org.inf.PERSISTENCE] (main) ISPN000554: jboss-marshalling is deprecated and planned for removal
2021-08-04 10:56:35,825 INFO  [org.inf.CONTAINER] (main) ISPN000128: Infinispan version: Infinispan 'Corona Extra' 11.0.9.Final
2021-08-04 10:56:35,906 INFO  [org.inf.PERSISTENCE] (main) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2021-08-04 10:56:36,160 INFO  [org.key.con.inf.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_160684, Site name: null
2021-08-04 10:56:36,776 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Wrong user name or password [28000-197]
2021-08-04 10:56:36,850 ERROR [org.key.cli.Picocli] (main) ERROR: Failed to start server using profile (dev).
2021-08-04 10:56:36,851 ERROR [org.key.cli.Picocli] (main) ERROR: Failed to obtain JDBC connection
2021-08-04 10:56:36,851 ERROR [org.key.cli.Picocli] (main) ERROR: Wrong user name or password [28000-197]
2021-08-04 10:56:36,851 ERROR [org.key.cli.Picocli] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
2021-08-04 10:56:36,852 INFO  [org.inf.man.DefaultCacheManager] (Thread-8) Stopping cache manager null on null
```

**Comment by DanielJoyce** [comment]
Per docs, I tried setting up db first. My understanding it can use h2 locally, and the above log has h2 errors

I tried 

```
❯ kc.sh --db=h2 --db-username=admin --db-password=1234abcd
Unknown option: '--db=h2'
Possible solutions: --db-password, --db-pool-max-size, --db-pool-min-size, --db-schema, --db-url, --db-username, --db-pool-initial-size
```

and it barfs, though the blog post announcing keycloak.X shows --db=postgres is valid

**Comment by DanielJoyce** [comment]
Ahh, fuirther down in the blog post it shows this as being a two step process

Out of the box, you need to set up at least H2 first

```
kc.sh config  --db=h2 --db-username=admin --db-password=1234abcd
```

**Comment by DanielJoyce** [comment]
Docs need to be improved.

**Comment by DanielJoyce** [comment]
--db=h2-file successfully builds config, but fails to start

```
❯ kc.sh config  --db=h2-file --db-username=admin --db-password=1234abcd
Updating the configuration and installing your custom providers, if any. Please wait.
Server configuration updated and persisted. Run the following command to review the configuration:

	kc.sh show-config


~/.local/bin took 5s 
❯ kc.sh show-config
Current Profile: none
Runtime Configuration:
	kc.config.args =   (KcSysPropConfigSource)
	kc.db =  h2-file (PersistedConfigSource)
	kc.db.password =  ******* (PersistedConfigSource)
	kc.db.username =  admin (PersistedConfigSource)
	kc.home.dir =  /home/danieljoyce/.local/bin/keycloak.x-15.0.0/bin/../ (KcSysPropConfigSource)
	kc.metrics.enabled =  false (PersistedConfigSource)
	kc.show.config =  none (KcSysPropConfigSource)
	kc.spi.theme.folder.dir =  /home/danieljoyce/.local/bin/keycloak.x-15.0.0/bin/..//themes (PersistedConfigSource)
	kc.version =  15.0.0 (KcSysPropConfigSource)
```

```
2021-08-04 11:35:22,568 WARN  [io.qua.run.con.ConfigChangeRecorder] (main) Build time property cannot be changed at runtime:
 - quarkus.package.type was 'fast-jar' at build time and is now 'mutable-jar'
2021-08-04 11:35:23,399 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Wrong user name or password [28000-197]
2021-08-04 11:35:23,400 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (main) HHH000342: Could not obtain connection to query metadata: org.h2.jdbc.JdbcSQLException: Wrong user name or password [28000-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.engine.Engine.validateUserAndPassword(Engine.java:341)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:165)
	at org.h2.engine.Engine.createSession(Engine.java:140)
	at org.h2.engine.Engine.createSession(Engine.java:28)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:351)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:124)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:189)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:210)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:490)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:472)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by DanielJoyce** [comment]
Using the standard h2 config, it doesn't seem to persist which would be a bit more ideal for local testing. It appears to default to h2:mem

**Comment by DanielJoyce** [comment]
Can confirm following config provides for db persistence:

`❯ kc.sh config  --db=h2 --db-url=jdbc:h2:file:~/keycloak.h2.db --db-username=admin --db-password=1234abcd`

Problem is kc.sh doesn't check if --db and --db-url are consistent and match. It's possible to have them refer to different things. 

--db=postgres --db-url=jdbc:h2:file  for example

**Comment by stianst** [comment]
This is not the correct place to report bugs in Keycloak. Please see https://www.keycloak.org/community for more information.
